[build]
publish = "site"
command = ""

[[redirects]]
from = "/security"
to = "/security.html"
status = 200

[[redirects]]
from = "/proof"
to = "/proof.html"
status = 200

[[redirects]]
from = "/resume"
to = "/resume.html"
status = 200

[[redirects]]
from = "/projects"
to = "/projects.html"
status = 200

[[redirects]]
from = "/lab"
to = "/lab.html"
status = 200

[[redirects]]
from = "/triage"
to = "/triage.html"
status = 200

[[redirects]]
from = "/case-study"
to = "/case-study.html"
status = 200

[[redirects]]
from = "/blog-python2-to-python3"
to = "/blog-python2-to-python3.html"
status = 200
